name: Trigger auto deployment for aca-helloworld-demo-educ-fc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aca-helloworld-demo-educ-fc-AutoDeployTrigger-12cbee8e-1e31-42fe-8ec7-226e18eac954.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrjskubeeducwe.azurecr.io
          username: ${{ secrets.ACAHELLOWORLDDEMOEDUCFC_REGISTRY_USERNAME }}
          password: ${{ secrets.ACAHELLOWORLDDEMOEDUCFC_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrjskubeeducwe.azurecr.io/aca-helloworld-demo-educ-fc:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAHELLOWORLDDEMOEDUCFC_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n aca-helloworld-demo-educ-fc -g rg-demo-aca-prd-fc --server acrjskubeeducwe.azurecr.io --username  ${{ secrets.ACAHELLOWORLDDEMOEDUCFC_REGISTRY_USERNAME }} --password ${{ secrets.ACAHELLOWORLDDEMOEDUCFC_REGISTRY_PASSWORD }}
            az containerapp update -n aca-helloworld-demo-educ-fc -g rg-demo-aca-prd-fc --image acrjskubeeducwe.azurecr.io/aca-helloworld-demo-educ-fc:${{ github.sha }}
