name: Trigger auto deployment for hello-world

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hello-world-AutoDeployTrigger-4a9537b1-dec2-4c92-aa2c-8e92c0f9447e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrjskubeeducwe.azurecr.io
          username: ${{ secrets.HELLOWORLD_REGISTRY_USERNAME }}
          password: ${{ secrets.HELLOWORLD_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrjskubeeducwe.azurecr.io/aca-helloworld-demo-educ-fc:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HELLOWORLD_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n hello-world -g rg-demo-aca-prd-fc --server acrjskubeeducwe.azurecr.io --username  ${{ secrets.HELLOWORLD_REGISTRY_USERNAME }} --password ${{ secrets.HELLOWORLD_REGISTRY_PASSWORD }}
            az containerapp update -n hello-world -g rg-demo-aca-prd-fc --image acrjskubeeducwe.azurecr.io/aca-helloworld-demo-educ-fc:${{ github.sha }}
