name: Trigger auto deployment for my-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/my-container-app-AutoDeployTrigger-b584679d-e48f-4a12-b947-99791df89504.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrforviademofc.azurecr.io
          registryUsername: ${{ secrets.MYCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: my-container-app
          resourceGroup: rg-aca-forvia-demo
          imageToBuild: acrforviademofc.azurecr.io/my-container-app:${{ github.sha }}
          dockerfilePath: Dockerfile


